/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Models.*;
import Controllers.*;
import java.awt.Font;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import javax.swing.table.JTableHeader;

class Pembayaran {
    String nama;
    int noAbsen;
    int jumlahBayar;
    
    public Pembayaran(String nama, int noAbsen, int jumlahBayar){
        this.nama = nama;
        this.noAbsen = noAbsen;
        this.jumlahBayar = jumlahBayar;
    }
}


/**
 *
 * @author ktyudha
 */
public class MainView extends javax.swing.JFrame {

    BookingFotoController controller = new BookingFotoController();

    int selectedLocationId;
    int selectedPackageId;
    int total;

    List<Paket> packages = new ArrayList();
    List<Pembayaran> pembayarans = new ArrayList();

    DefaultTableModel model;

    public MainView() {
        initComponents();
        
        

        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);

        descPkt.setEditable(false);

        String[] judul = {"#", "NAMA", "WhatsApp", "ALAMAT", "DETAIL ALAMAT", "WAKTU", "ACARA", "PAKET"};
        model = new DefaultTableModel(judul, 0);
        listBooking.setModel(model);

        JTableHeader header = listBooking.getTableHeader();
        header.setFont(new Font("Helvetica", Font.BOLD, 13));

        //DASHBOARD
        int countBook = controller.countOrder(1);
        String nCountBook = Integer.toString(countBook);
        countDashBook.setText(nCountBook);

        loadListBooking();
        loadLocation();
        loadCategory();

    }

    public void loadLocation() {
        List<Location> locations = controller.loadLocations();

        for (int i = 0; i < locations.size(); i++) {
            Location location = locations.get(i);
//            address.addItem(location.name);
System.out.println(""+location.name);
        }
    }

    public void loadCategory() {
        List<Category> categories = controller.loadCategories();

        for (int i = 0; i < categories.size(); i++) {
            Category category = categories.get(i);
            event.addItem(category.name);
        }
    }

    private void reloadPackagesDataSource(int category_id) {
        packages = controller.loadPackages(category_id);

        paket.removeAllItems();
        for (int i = 0; i < packages.size(); i++) {
            Paket pkt = packages.get(i);
            paket.addItem(pkt.name);
        }

    }

    private void loadListBook() {
        mainDash.removeAll();
        mainDash.repaint();
        mainDash.revalidate();

        //add panel
        mainDash.add(listMain);
        mainDash.repaint();
        mainDash.revalidate();
    }
    
    private void loadMainBook() {
        mainDash.removeAll();
        mainDash.repaint();
        mainDash.revalidate();

        //add panel
        mainDash.add(bookingMain);
        mainDash.repaint();
        mainDash.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        menuDash = new javax.swing.JPanel();
        btnDash = new javax.swing.JButton();
        btnBooking = new javax.swing.JButton();
        btnListBook = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        labelOrder = new javax.swing.JLabel();
        labelApp = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mainDash = new javax.swing.JPanel();
        dashMain = new javax.swing.JPanel();
        dashboard = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelDashBook = new javax.swing.JLabel();
        countDashBook = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelDashBook1 = new javax.swing.JLabel();
        countDashBook1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelDashBook2 = new javax.swing.JLabel();
        countDashBook2 = new javax.swing.JLabel();
        bookingMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelAddress = new javax.swing.JLabel();
        labelDetAddress = new javax.swing.JLabel();
        labelTime = new javax.swing.JLabel();
        labelEvent = new javax.swing.JLabel();
        labelPaket = new javax.swing.JLabel();
        labelTotPrize = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        detAddress = new javax.swing.JTextField();
        time = new javax.swing.JTextField();
        address = new javax.swing.JComboBox<>();
        paket = new javax.swing.JComboBox<>();
        event = new javax.swing.JComboBox<>();
        totPrice = new javax.swing.JLabel();
        btnOrder = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        descPkt = new javax.swing.JTextArea();
        phone = new javax.swing.JTextField();
        labelPhone = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        listMain = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listBooking = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyPanel.setPreferredSize(new java.awt.Dimension(900, 600));

        menuDash.setBackground(new java.awt.Color(87, 96, 111));

        btnDash.setBackground(new java.awt.Color(245, 245, 245));
        btnDash.setText("Dashboard");
        btnDash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashActionPerformed(evt);
            }
        });

        btnBooking.setText("Booking");
        btnBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingActionPerformed(evt);
            }
        });

        btnListBook.setText("List Booking");
        btnListBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListBookActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnAbout.setText("About");
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });

        labelOrder.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        labelOrder.setForeground(new java.awt.Color(255, 255, 255));
        labelOrder.setText("ORDER");

        labelApp.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        labelApp.setForeground(new java.awt.Color(255, 255, 255));
        labelApp.setText("APPLICATION");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/rsz_1cropped-logo-dhagrafis.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Kailasa", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DHAGRAFIS");

        javax.swing.GroupLayout menuDashLayout = new javax.swing.GroupLayout(menuDash);
        menuDash.setLayout(menuDashLayout);
        menuDashLayout.setHorizontalGroup(
            menuDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuDashLayout.createSequentialGroup()
                .addGroup(menuDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuDashLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(menuDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(btnDash)
                            .addGroup(menuDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAbout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnListBook, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(menuDashLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(menuDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelOrder)
                            .addComponent(labelApp))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        menuDashLayout.setVerticalGroup(
            menuDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuDashLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(62, 62, 62)
                .addComponent(btnDash)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBooking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListBook)
                .addGap(24, 24, 24)
                .addComponent(labelApp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAbout)
                .addGap(54, 54, 54)
                .addComponent(btnLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainDash.setBackground(new java.awt.Color(255, 255, 255));
        mainDash.setPreferredSize(new java.awt.Dimension(900, 600));
        mainDash.setLayout(new java.awt.CardLayout());

        dashMain.setBackground(new java.awt.Color(255, 255, 255));

        dashboard.setFont(new java.awt.Font("Jost", 1, 18)); // NOI18N
        dashboard.setText("DASHBOARD");

        jLabel5.setFont(new java.awt.Font("Jost", 0, 24)); // NOI18N
        jLabel5.setText("Selamat Datang di Aplikasi Booking Foto !!");

        jPanel1.setBackground(new java.awt.Color(30, 144, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelDashBook.setFont(new java.awt.Font("Jost", 0, 18)); // NOI18N
        labelDashBook.setForeground(new java.awt.Color(255, 255, 255));
        labelDashBook.setText("BOOKING");

        countDashBook.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        countDashBook.setForeground(new java.awt.Color(255, 255, 255));
        countDashBook.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(labelDashBook))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(countDashBook)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(countDashBook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDashBook)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(116, 185, 255));

        labelDashBook1.setFont(new java.awt.Font("Jost", 0, 18)); // NOI18N
        labelDashBook1.setForeground(new java.awt.Color(255, 255, 255));
        labelDashBook1.setText("FINISHED");

        countDashBook1.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        countDashBook1.setForeground(new java.awt.Color(255, 255, 255));
        countDashBook1.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(countDashBook1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(labelDashBook1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(countDashBook1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDashBook1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(30, 144, 255));

        labelDashBook2.setFont(new java.awt.Font("Jost", 0, 18)); // NOI18N
        labelDashBook2.setForeground(new java.awt.Color(255, 255, 255));
        labelDashBook2.setText("CANCELED");

        countDashBook2.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        countDashBook2.setForeground(new java.awt.Color(255, 255, 255));
        countDashBook2.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(countDashBook2)
                .addGap(115, 115, 115))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDashBook2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(countDashBook2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDashBook2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dashMainLayout = new javax.swing.GroupLayout(dashMain);
        dashMain.setLayout(dashMainLayout);
        dashMainLayout.setHorizontalGroup(
            dashMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashMainLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(dashMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(dashMainLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(dashMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(dashboard)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dashMainLayout.setVerticalGroup(
            dashMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashMainLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(dashboard)
                .addGap(50, 50, 50)
                .addGroup(dashMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jLabel5)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        mainDash.add(dashMain, "card2");

        bookingMain.setBackground(new java.awt.Color(255, 255, 255));
        bookingMain.setToolTipText("");
        bookingMain.setPreferredSize(new java.awt.Dimension(900, 600));

        jLabel1.setFont(new java.awt.Font("Jost", 1, 18)); // NOI18N
        jLabel1.setText("BOOKING FORM");

        labelName.setText("Nama Lengkap");

        labelAddress.setText("Alamat");

        labelDetAddress.setText("Detail Alamat");

        labelTime.setText("Waktu");

        labelEvent.setText("Acara");

        labelPaket.setText("Paket");

        labelTotPrize.setText("Harga");

        time.setText("dd-mm-yyy | 08:00 WIB");
        time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeActionPerformed(evt);
            }
        });

        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });

        paket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paketActionPerformed(evt);
            }
        });

        event.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventActionPerformed(evt);
            }
        });

        totPrice.setText("-");

        btnOrder.setBackground(new java.awt.Color(9, 132, 227));
        btnOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnOrder.setText("Pesan");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        jLabel3.setText("Deskripsi Paket");

        descPkt.setColumns(20);
        descPkt.setRows(5);
        descPkt.setText("  paket belum dipilih !!");
        jScrollPane3.setViewportView(descPkt);

        labelPhone.setText("Nomor WA");

        jLabel8.setText("Lokasi : Jalan Raya Pasar Krembung");

        jLabel9.setText("BCA a.n Kurniawan Try Yudha");

        jLabel10.setText("6140714613");

        javax.swing.GroupLayout bookingMainLayout = new javax.swing.GroupLayout(bookingMain);
        bookingMain.setLayout(bookingMainLayout);
        bookingMainLayout.setHorizontalGroup(
            bookingMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingMainLayout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookingMainLayout.createSequentialGroup()
                .addContainerGap(237, Short.MAX_VALUE)
                .addGroup(bookingMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bookingMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelName)
                        .addComponent(labelDetAddress)
                        .addComponent(labelTime)
                        .addComponent(labelEvent)
                        .addComponent(labelPaket)
                        .addComponent(labelTotPrize)
                        .addComponent(labelPhone)
                        .addComponent(labelAddress)))
                .addGap(32, 32, 32)
                .addGroup(bookingMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(address, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(time)
                    .addComponent(event, 0, 170, Short.MAX_VALUE)
                    .addComponent(paket, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(detAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(name, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(phone))
                .addGap(54, 54, 54)
                .addGroup(bookingMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(79, 79, 79))
        );
        bookingMainLayout.setVerticalGroup(
            bookingMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingMainLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addGroup(bookingMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(bookingMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookingMainLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(bookingMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPhone))
                        .addGap(9, 9, 9)
                        .addGroup(bookingMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAddress)
                            .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bookingMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDetAddress)
                            .addComponent(detAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(bookingMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTime))
                        .addGap(16, 16, 16)
                        .addGroup(bookingMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEvent)
                            .addComponent(event, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bookingMainLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bookingMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookingMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(paket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addComponent(labelPaket))
                .addGroup(bookingMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookingMainLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bookingMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTotPrize)
                            .addComponent(totPrice)))
                    .addGroup(bookingMainLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addComponent(btnOrder)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        mainDash.add(bookingMain, "card3");

        listMain.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Jost", 1, 18)); // NOI18N
        jLabel2.setText("BOOKING LIST");

        listBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No.", "Nama", "Alamat", "Detail Alamat", "Waktu", "Acara", "Paket"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listBooking.setGridColor(new java.awt.Color(255, 255, 255));
        listBooking.setIgnoreRepaint(true);
        listBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listBookingMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listBooking);

        btnDelete.setBackground(new java.awt.Color(255, 51, 51));
        btnDelete.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(255, 204, 0));
        btnEdit.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listMainLayout = new javax.swing.GroupLayout(listMain);
        listMain.setLayout(listMainLayout);
        listMainLayout.setHorizontalGroup(
            listMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listMainLayout.createSequentialGroup()
                .addGroup(listMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(listMainLayout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(jLabel2))
                    .addGroup(listMainLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(listMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(listMainLayout.createSequentialGroup()
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        listMainLayout.setVerticalGroup(
            listMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listMainLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(listMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnEdit))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        mainDash.add(listMain, "card4");

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addComponent(menuDash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mainDash, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuDash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainDash, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashActionPerformed
        // TODO add your handling code here:

        //remove panel
        mainDash.removeAll();
        mainDash.repaint();
        mainDash.revalidate();

        //add panel
        mainDash.add(dashMain);
        mainDash.repaint();
        mainDash.revalidate();
    }//GEN-LAST:event_btnDashActionPerformed

    private void btnBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingActionPerformed
        // TODO add your handling code here:
        loadMainBook();
       
    }//GEN-LAST:event_btnBookingActionPerformed

    private void btnListBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListBookActionPerformed
        // TODO add your handling code here:
        loadListBook();
    }//GEN-LAST:event_btnListBookActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Anda yakin keluar?", "PERINGATAN", dialogBtn);

        if (dialogResult == 0) {
            this.dispose();
            new LoginView().setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        // TODO add your handling code here:

        AboutView about = new AboutView();
        about.setVisible(true);
    }//GEN-LAST:event_btnAboutActionPerformed

    private void eventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventActionPerformed
        // TODO add your handling code here:
        int selectedCategoryId = event.getSelectedIndex();
        this.reloadPackagesDataSource(selectedCategoryId);
    }//GEN-LAST:event_eventActionPerformed

    private void paketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paketActionPerformed
        // TODO add your handling code here:
        if (paket.getSelectedIndex() >= 1) {
            Paket pkt = packages.get(paket.getSelectedIndex());
            selectedPackageId = pkt.id;

            String pktID = controller.loadDescPkt(selectedPackageId);
            descPkt.setText(pktID);

            total = controller.calculatePrice(selectedLocationId, selectedPackageId);
            String totalPrice = Integer.toString(total);
            totPrice.setText(totalPrice);
        }
    }//GEN-LAST:event_paketActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        // TODO add your handling code here:

        try {

            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dhagrafis", "root", "calonmertua2002");
//        

            String sql = "insert into orders (nama,phone, detailalamat, waktu, paket_id, user_id, category_id, total, location_id)" + " values(?,?,?,?,?,?,?,?,?)";
//     

            PreparedStatement preparedStmt = conn.prepareStatement(sql);

            int selectPkt = paket.getSelectedIndex();
            int ctgr = event.getSelectedIndex();
            int loc = address.getSelectedIndex();

            //category
            preparedStmt.setString(1, name.getText());
            preparedStmt.setString(2, phone.getText());
            preparedStmt.setString(3, detAddress.getText());
            preparedStmt.setString(4, time.getText());
            preparedStmt.setInt(5, selectPkt);  //paket_id
            preparedStmt.setInt(6, 1);     //user_id
            preparedStmt.setInt(7, ctgr);     //category_id
            preparedStmt.setString(8, totPrice.getText());     //total
            preparedStmt.setInt(9, loc);        //location_id

            preparedStmt.execute();
            conn.close();

            JOptionPane.showMessageDialog(null, "Anda berhasil Booking !!\nsegera lakukan pembayaran");
            loadListBooking();
            loadListBook();
        } catch (SQLException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnOrderActionPerformed

    private void listBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listBookingMouseClicked
        // TODO add your handling code here:
        int i = listBooking.getSelectedRow();

    }//GEN-LAST:event_listBookingMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:

        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Anda yakin Hapus?", "PERINGATAN", dialogBtn);

        if (dialogResult == 0) {
            int i = listBooking.getSelectedRow();

            try {

                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dhagrafis", "root", "calonmertua2002");

                String sql = "delete from orders where id=" + model.getValueAt(i, 0);
                PreparedStatement preparedStmt = conn.prepareStatement(sql);
                preparedStmt.execute();
                conn.close();
                loadListBooking();
                loadListBook();

            } catch (SQLException e) {
                System.out.println("gagal menghapus");
            }
        }


    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:

        int i = listBooking.getSelectedRow();

        if (i >= 0) {
            name.setText(model.getValueAt(i, 1).toString());
            phone.setText(model.getValueAt(i, 2).toString());
            address.setSelectedItem(model.getValueAt(i, 3));
            detAddress.setText(model.getValueAt(i, 4).toString());
            time.setText(model.getValueAt(i, 5).toString());
            event.setSelectedItem(model.getValueAt(i, 6));
            paket.setSelectedItem(model.getValueAt(i, 7));
        }
        
        loadMainBook();

    }//GEN-LAST:event_btnEditActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
        selectedLocationId = address.getSelectedIndex();
        total = controller.calculatePrice(selectedLocationId, selectedPackageId);
        String totalPrice = Integer.toString(total);
        totPrice.setText(totalPrice);
    }//GEN-LAST:event_addressActionPerformed

    private void timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
//                new MainView().setVisible(true);
            }
        });
    }

    private void loadListBooking() {
        int row = listBooking.getRowCount();
        for (int i = 0; i < row; i++) {
            model.removeRow(0);
        }
        listBooking.removeAll();
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dhagrafis", "root", "calonmertua2002");
            Statement s = conn.createStatement();

            ResultSet rs = s.executeQuery(" SELECT *  FROM orders INNER JOIN users ON orders.user_id = users.id INNER JOIN categories ON orders.category_id = categories.id INNER JOIN pakets ON orders.paket_id = pakets.id INNER JOIN locations ON orders.location_id = locations.id ORDER BY orders.id DESC");
            while (rs.next()) {
                
                String data[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(24), rs.getString(4), rs.getString(5), rs.getString(17), rs.getString(19)};
                model.addRow(data); 
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> address;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JPanel bookingMain;
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnBooking;
    private javax.swing.JButton btnDash;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnListBook;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOrder;
    private javax.swing.JLabel countDashBook;
    private javax.swing.JLabel countDashBook1;
    private javax.swing.JLabel countDashBook2;
    private javax.swing.JPanel dashMain;
    private javax.swing.JLabel dashboard;
    private javax.swing.JTextArea descPkt;
    private javax.swing.JTextField detAddress;
    private javax.swing.JComboBox<String> event;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelApp;
    private javax.swing.JLabel labelDashBook;
    private javax.swing.JLabel labelDashBook1;
    private javax.swing.JLabel labelDashBook2;
    private javax.swing.JLabel labelDetAddress;
    private javax.swing.JLabel labelEvent;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelOrder;
    private javax.swing.JLabel labelPaket;
    private javax.swing.JLabel labelPhone;
    private javax.swing.JLabel labelTime;
    private javax.swing.JLabel labelTotPrize;
    private javax.swing.JTable listBooking;
    private javax.swing.JPanel listMain;
    private javax.swing.JPanel mainDash;
    private javax.swing.JPanel menuDash;
    private javax.swing.JTextField name;
    private javax.swing.JComboBox<String> paket;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField time;
    private javax.swing.JLabel totPrice;
    // End of variables declaration//GEN-END:variables
}
